name: Process Single Repository

on:
  workflow_dispatch:
    inputs:
      subfolder:
        description: 'Subapsta de data a ser processada (ex: spring-boot)'
        required: true
      repo:
        description: 'OWNER e REPO (ex: spring-projects/spring-boot)'
        required: true

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydriller

    - name: Clone REPOSITORY repos_dir
      run: |
        mkdir -p repos_dir
        cd repos_dir
        git clone https://github.com/${{ github.event.inputs.repo }}.git

    - name: Process repository
      run: |
        python process_single_repo.py \
          --subfolder "${{ github.event.inputs.subfolder }}"

    - name: Commit and push
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add data_with_metrics/*
        git commit -m "Add metrics for data"
        git push
