name: Run PyDriller - Grosa
on:
  workflow_dispatch:
      
jobs:

  list-json-files:
    runs-on: ubuntu-latest

    outputs:
      json_files: ${{ steps.list-json-files.outputs.json_files }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: List JSON files
      id: list-json-files
      run: |
        files=$(ls json/raw_data/bics*.json | jq -R -s -c 'split("\n")[:-1]')
        echo files=$files
        echo "json_files=$files" >> $GITHUB_OUTPUT

  run-script:
    needs: list-json-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{fromJson(needs.list-json-files.outputs.json_files)}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Create json folder 
      run: |
        mkdir -p json/bics/  

    - name: Clone pyszz_v2
      uses: actions/checkout@v4.1.6
      with:
        repository: 'thiagogquinto/pyszz_v2'
        path: 'pyszz_v2'
        ref: 'tcc_version'

    - name: Clone JabRef to pyszz_v2/repos_dir
      run: |
        mkdir -p pyszz_v2/repos_dir
        cd pyszz_v2/repos_dir
        git clone https://github.com/elastic/elasticsearch.git
      
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Run pyszz_v2
      working-directory: pyszz_v2/
      run: |
        echo "$(basename ${{ matrix.file }})"
        cp ../${{ matrix.file }} issues_data.json
        bash run_docker.sh issues_data.json conf/pdszz_issues_filter.yml /repos_dir/

    - name: Bring out file to main folder
      working-directory: pyszz_v2/
      run: |
        filename=$(basename ${{ matrix.file }})
        cp out/bics.json ../json/bics/bics_$filename
  
    - name: Commit and push
        # git add logs/*
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add json/bics/*.json
        git commit -m "Add bics files - PyDriller"
        git push
